<?php if ($this->isEnabled()): ?>
<script>
    const cdnUrl   = '<?= $this->getMediaUrl() ?>';
    const mediaUrl = '<?= $this->getBaseMediaUrl() ?>';

    var replacedImages = [];

    document.addEventListener('error', (event) => {
        if (event.target.tagName.toLowerCase() !== 'img') return;
        const url = event.target.src.split('?')[0];
        if (replacedImages.includes(url)) return;
        replacedImages.push(url);
        event.target.src = url.replace(cdnUrl, mediaUrl) + '?imgstore=<?= $this->getStoreCode() ?>';

        if(event.target.offsetParent.tagName.toLowerCase() == 'picture') {
            const sources = event.target.offsetParent.querySelectorAll('source');
            sources.forEach(function(source) {
                let url = source.srcset.split('?')[0];
                if (replacedImages.includes(url)) return;
                replacedImages.push(url);
                source.srcset = url.replace(cdnUrl, mediaUrl) + '?imgstore=<?= $this->getStoreCode() ?>';
            });
        }
    }, {
        capture: true,
        once: false,
        passive: true
    });
</script>
<?php endif; ?>
